### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by srnyx** [Globox1997/VoidZ#1]
What does this add/do?

**Comment by Globox1997** [comment]
Will be an addon for AdventureZ and adds a void dimension only for a boss fight against the Void Shadow.
The reason for it to be an addon is, the fabric api has no guarantee to update their teleport api when update 1.17 will come out and the chance is pretty high it will take a while to update it and AdventureZ should get updated quickly

**Comment by srnyx** [comment]
So will this work on 1.16.5 if I use it right now?

**Comment by Globox1997** [comment]
probably not, it is still in development
