### ISSUE TITLE
In better minecraft (fabric), the portal back from the void dimension places the player in bedrock.

### ISSUE THREAD

**Issue by madswolf** [Globox1997/VoidZ#10]
I tested in singleplayer and multiplayer and it produced the same result.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VoidZ/commit/7292a351f39f1d341dd7d849ae076ee3e28b4194](https://github.com/Globox1997/VoidZ/commit/7292a351f39f1d341dd7d849ae076ee3e28b4194)
