### ISSUE TITLE
Multiple Void shadows Causes Crashloops Multiplayer

### ISSUE THREAD

**Issue by BarBreaker** [Globox1997/VoidZ#11]
### [BUG]
Completing the eye fight and spawning the portal to fight the Void Shadow can lead to the issue of multiple void shadows spawning, which causes a crashloop if one dies and the other is still alive. Everything behaves as normal until one of the entities dies. I am unsure if this issue is caused by multiple portals remaining and each portal spawning it's own instance of the boss, or if the issue is caused by me joining mid-fight to help my friend. Further testing is required.

**Comment by Globox1997** [comment]
Does a second void shadow spawn when two players teleport into the void with the same portal?

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VoidZ/commit/7292a351f39f1d341dd7d849ae076ee3e28b4194](https://github.com/Globox1997/VoidZ/commit/7292a351f39f1d341dd7d849ae076ee3e28b4194)
