### ISSUE TITLE
How to remove Voidz from SaveFiles

### ISSUE THREAD

**Issue by DSBash** [Globox1997/VoidZ#14]
Hello, while playing around with Paper and BetterMC 1.18.2 mod pack, changes were made to the World save and it will no longer load in Forge. (PS we did not go to the Void Dimension)
Is there a way to remove the Voidz changes from the Savefiles so the world can be saved?

This is the error that causes the Server to Crash.
WorldGenSettings: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: voidz:void missed input

**Comment by Globox1997** [comment]
Even if you didn't go to the void dimension, it should got generated, so my only idea to fix this is to delete the void dimension in the dimensions folder

**Comment by DSBash** [comment]
Thanks for the quick follow up!
I was able to determine a file in the main data folder was causing the issue.
