### ISSUE TITLE
Failed to find void world, was it registerd?

### ISSUE THREAD

**Issue by Lebenwesen** [Globox1997/VoidZ#16]
Der Titel sagt leider alles. Irgendwie wurden einige Dimension nicht erstellt beim Server aufsetzen. Eine davon ist die VoidZ. Weißt du zufällig wie ich die neu generieren lassen kann oder hinzufügen kann?

**Comment by Globox1997** [comment]
Dimensions usually load when the game starts, did you fix it?

**Comment by Lebenwesen** [comment]
Yes I fixes it. I used the NBTExplorer and Put the Generator vor the void, etc. In the world where it wasnt generated. And Thema everything was fine

**Comment by Globox1997** [comment]
Great you figured it out :)
