### ISSUE TITLE
Incompatible with TerraBlender

### ISSUE THREAD

**Issue by Rad586** [Globox1997/VoidZ#17]
[latest.log](https://github.com/Globox1997/VoidZ/files/9103947/latest.log)
In 1.18.1, the game crashes without popping up the window with these two mods installed.
Version:
TerraBlender-fabric-1.18.1-1.1.0.77
voidz-1.0.5

**Comment by Globox1997** [comment]
Pls update to a later version, out of time reasons I only work on the latest version
