### ISSUE TITLE
Crash when hitting the crystals of the void shadow

### ISSUE THREAD

**Issue by ChaoticFrEnZ** [Globox1997/VoidZ#18]
Imj playing in the Origins adventures modpack, and im fighting the Void shadow but everytime a bullet from the other shadow thingies hit a crystal, my game crashes
![crash](https://user-images.githubusercontent.com/109575395/179675603-c68f5951-cdc2-4968-aa90-6d692688c34a.png)
.

**Comment by Globox1997** [comment]
Which mod version is this and pls post the full crash log
