### ISSUE TITLE
[QUESTION] Adding to world

### ISSUE THREAD

**Issue by srnyx** [Globox1997/VoidZ#2]
Can I add this to my server that has already been played on safely?

**Comment by Globox1997** [comment]
I'm pretty sure yes :) Please send feedback for anything

**Comment by srnyx** [comment]
> I'm pretty sure yes :) Please send feedback for anything 

I'll back my server up just in-case and tell you how it goes.

**Comment by srnyx** [comment]
@Globox1997 Is it supposed to look like this?
![img](https://max-is.an-idiot.xyz/r/kpkhxd65d9a.png)

**Comment by Globox1997** [comment]
The background looks like it's from betterend mod but it surprises me that vanilla mobs spawn there

**Comment by srnyx** [comment]
> The background looks like it's from betterend mod

Yeah, I'm using BetterEnd.

> it surprises me that vanilla mobs spawn there

The Void mobs aren't even there cause of https://github.com/Globox1997/VoidZ/issues/3. And maybe there is another mod conflicting. Once the new version of my modpack is Approved on CurseForge, I can send it to you.

**Comment by Globox1997** [comment]
Mob spawn is fixed with [https://github.com/Globox1997/VoidZ/commit/7c72c670011773317cd835b6399a2943cd432fd9](https://github.com/Globox1997/VoidZ/commit/7c72c670011773317cd835b6399a2943cd432fd9)
