### ISSUE TITLE
Void Portal not working

### ISSUE THREAD

**Issue by NitroxydeX** [Globox1997/VoidZ#20]
After defeating The Eye it spawned the mentioned portal, but nothing happens when dropping into it. It seems that something is there which makes the player kinda stuck but nothing happens.

Any ideas?

Using VoidZ 1.0.9 and AdventureZ 1.4.17

![2023-01-02_21 45 38](https://user-images.githubusercontent.com/9305576/210276859-8fb62859-925f-4c32-8c0c-a1c15aa42fd2.png)

**Comment by Globox1997** [comment]
Try to right click on the portal block

**Comment by Globox1997** [comment]
Reopen if right click does not work on the portal.
