### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by benio1394** [Globox1997/VoidZ#21]
https://pastebin.com/tiU1EneB

**Comment by lxly9** [comment]
same here!

**Comment by Globox1997** [comment]
This seems like an incompatibility with another mod, if you figure out which one, I will look into it.

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/VoidZ/commit/3f85ceea652cc52357b3ae5a12ecf10ba70c464d](https://github.com/Globox1997/VoidZ/commit/3f85ceea652cc52357b3ae5a12ecf10ba70c464d)
