### ISSUE TITLE
Crashing in 1.20 when creating VoidZ portal

### ISSUE THREAD

**Issue by ghost** [Globox1997/VoidZ#22]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.0.9

### Describe the Issue

When the eye is killed it crashes the game when attempting to spawn the portal block.

### latest.log

[latest.log](https://github.com/Globox1997/VoidZ/files/11738411/latest.log)
[crash-2023-06-13_12.12.13-server.txt](https://github.com/Globox1997/VoidZ/files/11738414/crash-2023-06-13_12.12.13-server.txt)

### Do you use any other mods except the required ones?

No, I only had those two mods on.

**Comment by Mahadbaloch** [comment]
I am having this issue too. The world cannot be joined once the eye is killed and will repeatedly crash.
[crash-2023-07-28_03.17.52-server.txt](https://github.com/Globox1997/VoidZ/files/12188564/crash-2023-07-28_03.17.52-server.txt)

**Comment by Globox1997** [comment]
Do you use the latest versions of AdventureZ and VoidZ?

**Comment by Mahadbaloch** [comment]
I have the latest 1.20 version, 1.0.9, same for adventurez(1.4.18)

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/VoidZ/commit/3f85ceea652cc52357b3ae5a12ecf10ba70c464d](https://github.com/Globox1997/VoidZ/commit/3f85ceea652cc52357b3ae5a12ecf10ba70c464d)
