### ISSUE TITLE
Server crash after kill boss

### ISSUE THREAD

**Issue by mindryder** [Globox1997/VoidZ#23]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-api-0.88.1+1.20.1

### Mod Version

voidz-1.0.10

### Describe the Issue

Server crash after kill boss

### latest.log

[crash-2023-09-05_20.15.26-server.txt](https://github.com/Globox1997/VoidZ/files/12526609/crash-2023-09-05_20.15.26-server.txt)
[crash-2023-09-05_20.38.59-server.txt](https://github.com/Globox1997/VoidZ/files/12526610/crash-2023-09-05_20.38.59-server.txt)

**Comment by Voitec8593** [comment]
Having the same issue in singleplayer

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/VoidZ/commit/3f85ceea652cc52357b3ae5a12ecf10ba70c464d](https://github.com/Globox1997/VoidZ/commit/3f85ceea652cc52357b3ae5a12ecf10ba70c464d)
