### ISSUE TITLE
Void dimension spawn point causes player to fall into the void, because void portal a fall through block

### ISSUE THREAD

**Issue by TeslaP09** [Globox1997/VoidZ#24]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.24

### Mod Version

1.0.10

### Describe the Issue

The spawnpoint in the void dimension is 0, 100, 0 so the player spawns directly on top of the void portal that leads back to the overworld. This wasn't a problem in previous versions (see some let's plays on youtube, e.g. https://youtu.be/0uN_h1Xrt_s?feature=shared&t=95), but in newer versions the void portal block is a walk through block, meaning that the player will immediately fall into the void on spawning in the void dimension, without being able to save themselves. 

(Issue tested on both fabric 0.14.24 and quilt 0.21.1 with only AdventureZ, VoidZ and Cloth Config API installed)
The log file doesn't show anything relevant, though included it anyway just to be safe.

Also I still have kind of the same issue as #10, so when I return to the overworld, I SOMETIMES spawn somewhere underground (for example on height 50, even though I shouldn't spawn anywhere below ~63)

### latest.log

[latest.log](https://github.com/Globox1997/VoidZ/files/13252076/latest.log)

### Do you use any other mods except the required ones?

Nope, only AdventureZ, VoidZ and Cloth Config API

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VoidZ/commit/e3661c4e5ed2a5227b432290ae49e672c34dec97](https://github.com/Globox1997/VoidZ/commit/e3661c4e5ed2a5227b432290ae49e672c34dec97)
Changed portal block to a solid block.
