### ISSUE TITLE
Ability to resummon or restart the Void Shadow boss fight

### ISSUE THREAD

**Issue by etendards** [Globox1997/VoidZ#26]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

On a server and I cant find a way to resummon this boss.

**Comment by Globox1997** [comment]
You have to edit the voidz config, there is an option for it.

**Comment by etendards** [comment]
How would we know how to do it?  Is it in the wiki or mod book?

**Comment by Globox1997** [comment]
Just check the config options :)

**Comment by Lumb3rSamur4i** [comment]
> Just check the config options :)

Same problem for me, this my config file
![image](https://github.com/user-attachments/assets/802709a7-1067-4214-a6d8-89b914d55dba)
