### ISSUE TITLE
Game crashes after defeating the boss

### ISSUE THREAD

**Issue by gamertag84** [Globox1997/VoidZ#29]
### Minecraft Version

1.20.x

### Mod Loader Version

1.20.1

### Mod Version

1.0.11

### Describe the Issue

After defeating the boss the game crashes

### latest.log

[latest.log](https://github.com/user-attachments/files/16227618/latest.log)

### Do you use any other mods except the required ones?

Yes

**Comment by Globox1997** [comment]
Incompat with majruszlibrary mod

**Comment by gamertag84** [comment]
Yeah, that fixed it. Thanks
