### ISSUE TITLE
shadow chest didnt generating enchanted books 

### ISSUE THREAD

**Issue by Ice-Witcher** [Globox1997/VoidZ#31]
### Minecraft Version

1.21.x

### Mod Loader Version

fabric 0.16.0

### Mod Version

1.0.11

### Describe the Issue

when i open shadow chest, enchanted books dont have any enchant like sharpnes VI it is only enchanted book

### latest.log

![image](https://github.com/user-attachments/assets/97da3ce2-6d69-4332-9386-9b4f122f36e0)
![obraz_2024-08-17_170953755](https://github.com/user-attachments/assets/10d9806b-2851-4d35-9cfe-64dc3f963c1f)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/56e42e53afa3ca9192082a1d8db83ad0ef10497f](https://github.com/Globox1997/AdventureZ/commit/56e42e53afa3ca9192082a1d8db83ad0ef10497f)
