### ISSUE TITLE
[SUGGESTION] Only spawn one boss, multiplayer

### ISSUE THREAD

**Issue by srnyx** [Globox1997/VoidZ#4]
4 people in my server just entered the dimension at the same time... let's just say it's a bit chaotic:
![img](https://max-is.an-idiot.xyz/r/kplf0m76a9a.png)

**Comment by srnyx** [comment]
Also, how do you defeat the boss (properly [we had to fly and hit it with our swords])? lol
Maybe add it to the AdventureZ guidebook.

**Comment by Globox1997** [comment]
elytra should be disabled in this dimension so idk how you can fly there :D
if you read the guidebook precisely, it explains how to defeat the boss :)

**Comment by srnyx** [comment]
> elytra should be disabled in this dimension so idk how you can fly there :D

Angel Ring from [Kibe](https://www.curseforge.com/minecraft/mc-mods/kibe)

> if you read the guidebook precisely, it explains how to defeat the boss :)

Yeah, I saw about the Void Orb and stuff, but it just didn't make much sense. It was extremely hard to do with multiple people because the bullets were all going in different directions. And it doesn't make a lot of sense why the Void Orbs would even do damage to the bosses.

**Comment by Globox1997** [comment]
sounds like kibe has op items^^
they are connected to the boss and you can hit the void bullets into the orb direction :)

**Comment by srnyx** [comment]
> sounds like kibe has op items^^

The Angel Ring is something that I wish could only be used in areas claimed with Flan. Actually, I'm going to go suggest it right now. Ok, I suggested it.

> they are connected to the boss and you can hit the void bullets into the orb direction :)

Ohhhhh, I didn't know you could redirect the bullets. I think it was only super challenging because when people would be flying, the bullets would go up, into the air, instead of straight ahead.

**Comment by Globox1997** [comment]
I guess I can close this, cause now there will spawn only one boss regardless of how many players will port to the void

**Comment by srnyx** [comment]
> I guess I can close this, cause now there will spawn only one boss regardless of how many players will port to the void

Is it possible to make it once every like hour **and** per player? That way every player can fight it but multiple won't be spawned when a group of people teleport.

**Comment by Globox1997** [comment]
The goal of the void boss is to be the very end boss, so a one time fight but what about a config for it

**Comment by srnyx** [comment]
> what about a config for it

Yeah a config would be nice

And what I meant before is that there would be a 1-hour cooldown, and it can be only be summoned once per player.
Example:
1. I go into the dimension
2. A few other people go into the dimension
2. 1 Void Boss spawns
3. We kill it (the drops go to the person that first entered the dimension, so me)
4. We leave the dimension and then go back into it
5. The Void Boss *won't* spawn because it's on cooldown
6. 1 hour later someone else goes in
7. Repeat 2 and 3

**Comment by Globox1997** [comment]
Added this mechanic with [https://github.com/Globox1997/VoidZ/commit/88f918b75a244fe06b1fdd4fb88e229c221046fd](https://github.com/Globox1997/VoidZ/commit/88f918b75a244fe06b1fdd4fb88e229c221046fd)
There is a config setting to enable this and after what time it will respawn
