### ISSUE TITLE
Void Shadow invicible

### ISSUE THREAD

**Issue by Nobola** [Globox1997/VoidZ#8]
Void Shadow cannot be hit or killed

**Comment by Globox1997** [comment]
the void shadow is immune against arrows but can be hit with a sword.
it will run from time to time to the middle of the void and cast some spells when it is under half life.
so the only way to damage it before it has half hp, is to kill the void orbs by either running into them (which will damage you) or by shooting them with a void bullet which can get dodged or just pushed back (in the direction you are hitting) which should be explained in the adventurez handbook (craftable at the smithing table with a normal book and an orc skin when patchouli mod is installed)
